### ISSUE TITLE
[Bug] CustomOre not generating with cofh

### ISSUE THREAD

**Issue by Slater022** [The-Acronym-Coders/B.A.S.E#49] opened 2017-04-10 18:15 UTC
![image](https://cloud.githubusercontent.com/assets/3940371/24875960/2f7e54cc-1e2a-11e7-8bc9-9153c02f491b.png)
![image](https://cloud.githubusercontent.com/assets/3940371/24876101/b72a040c-1e2a-11e7-8ac1-e5cf82297dde.png)

with this config : 
```

{
  "populate": {
    "osmiumVein": {
      "distribution": "uniform",
      "generator": {
        "block": [
          {
            "name": "base:osmium.ore",
            "weight": 50
          },
          {
            "name": "base:osmium.poor_ore",
            "weight": 50
          }
        ],
        "material": "stone",
        "cluster-size": 17
      },
      "cluster-count": 20,
      "min-height": 0,
      "max-height": 128,
      "retrogen": false,
      "biome": "all",
      "dimension": {
        "restriction": "blacklist",
        "value": [
          -1,
          1
        ]
      }
    }
  }
}
```

Not working at all ^^"

**Comment by Lanse505** [comment] 2017-04-10 18:17
Could you post your latest log so I could have a look?

**Comment by Slater022** [comment] 2017-04-10 18:30
Yes : 
```
[20:30:52] [Server thread/INFO]: Found 3 World Generation files and 0 folders present in C:\Users\Touhma\WebstormProjects\callistopack\config\cofh\world.
[20:30:52] [Server thread/INFO]: Reading world generation info from: cofh\world\vanilla.json:
[20:30:52] [Server thread/INFO]: Finished reading cofh\world\vanilla.json
[20:30:52] [Server thread/INFO]: Reading world generation info from: cofh\world\vanilla_poor.json:
[20:30:52] [Server thread/INFO]: Finished reading cofh\world\vanilla_poor.json
[20:30:52] [Server thread/INFO]: Reading world generation info from: cofh\world\vanilla_regular_gems.json:
**[20:30:52] [Server thread/ERROR]: Invalid block entry!**
[20:30:52] [Server thread/WARN]: Invalid generator for 'osmiumvein'!
[20:30:52] [Server thread/WARN]: Template 'uniform' failed to parse its entry!
[20:30:52] [Server thread/ERROR]: Error parsing generation entry: 'osmiumvein' > Please check the parameters.
[20:30:52] [Server thread/INFO]: Finished reading cofh\world\vanilla_regular_gems.json
[20:30:52] [Server thread/INFO]: [Touhma: Successfully reloaded World Generators.]
[20:30:52] [Client thread/INFO]: [CHAT] Successfully reloaded World Generators.
```

For the short version :) 

For the complete : 
https://pastebin.com/11r9q1rs

COFH_core : CoFHCore-1.10.2-4.1.1.156-universal

**Comment by SkySom** [comment] 2017-04-10 18:37
http://teamcofh.com/docs/cofh-core/features/custom-world-generation/#template-types
According to this, the issue is with your script. You need minHeight/maxHeight, not min-height/max-height

**Comment by Slater022** [comment] 2017-04-10 18:41
Wrong : According to the 1.10 wiki : 
https://github.com/CoFH/cofh.github.io/tree/1.10-updates/docs

No more Camelcase ...

**Comment by covers1624** [comment] 2017-04-10 18:42
The wiki is currently being updated and basically everything has been moved from "cammelCase" to "snake-case"

**Comment by Slater022** [comment] 2017-04-10 18:43
Example of working file : 
https://pastebin.com/GWifHATY

Result : 
![image](https://cloud.githubusercontent.com/assets/3940371/24877184/a5494fc8-1e2e-11e7-834b-783433e66c3d.png)

**Comment by SkySom** [comment] 2017-04-10 18:44
Fair enough, but still it's the script failing to parse? I'm not sure how this is our issue?

**Comment by Slater022** [comment] 2017-04-10 18:47
I think that is the name of the block : you use base:osmium.ore, for railcraft for example it's : 
"name": "railcraft:ore",
            "metadata": 5

Can't try with base:osmiumore for example. it's maybe the dot that cause the parsing to fail

**Comment by SkySom** [comment] 2017-04-10 18:49
Well yes you can't try with base:osmiumore, because that's not it's registry name.

**Comment by Slater022** [comment] 2017-04-10 18:53
Exactly what i'm saying xD the problem can came from the registry name ^^

**Comment by SkySom** [comment] 2017-04-10 18:54
So if you replace the name (With some other random block) in the erroring script, does it work

**Comment by Slater022** [comment] 2017-04-10 19:01
yep : 
![image](https://cloud.githubusercontent.com/assets/3940371/24877776/d656f690-1e30-11e7-88cd-9fa53fd955c5.png)
```

{
  "populate": {
    "osmiumvein": {
      "distribution": "uniform",
      "generator": {
        "block": [
          {
            "name": "minecraft:redstone_ore",
            "weight": 50
          },
          {
            "name": "minecraft:lapis_ore",
            "weight": 50
          }
        ],
        "material": "stone",
        "cluster-size": 17
      },
      "cluster-count": 20,
      "min-height": 0,
      "max-height": 128,
      "retrogen": true,
      "biome": "all",
      "dimension": {
        "restriction": "blacklist",
        "value": [
          -1,
          1
        ]
      }
    }
  }
}

```

**Comment by Slater022** [comment] 2017-04-10 19:42
Custom ore gen say me that : 
------ Error Message ------

java.lang.IllegalStateException: Ore block descriptor for vnlaOsmiumVeins is empty or does not match any registered blocks.
with the block : ` "<OreBlock block='base:osmium.poor_ore' weight='1.0' />"`

**Comment by Lanse505** [comment] 2017-04-10 19:43
We're dealing with the bug atm, please do not open up issues or poke people about it unless sufficient time has elapsed. We're working as fast as we can to resolve the issue so please be patient.

**Comment by SkySom** [comment] 2017-05-31 14:14
Closing this, as there's no real way to change the . to a _ without breaking prior registry names for V1, feel free to try with the new V2 of Materials that is now part of ContentTweaker. See https://github.com/The-Acronym-Coders/ContentTweaker/wiki/Materials-V2-Test for an example.

**Closed as completed by SkySom** 2017-05-31 14:14 UTC
Labels: Mod Interaction, More Info Needed
